// * USER INPUT ******
export const ADD_ROOM_DIMENSION = 'ADD_ROOM_DIMENSION'; 
export const ADD_ROOMBA_LOCATION = 'ADD_ROOMBA_LOCATION';
export const ADD_DIRT_LOCATION = 'ADD_DIRT_LOCATION'; 
export const ADD_DRIVING_INSTRUCTIONS = 'ADD_DRIVING_INSTRUCTIONS'; 
export const BACKSPACE_DRIVING_INSTRUCTIONS = 'BACKSPACE_DRIVING_INSTRUCTIONS'; 
export const CLEAR_DRIVING_INSTRUCTIONS = 'CLEAR_DRIVING_INSTRUCTIONS'; 
// ******************

export const ADD_SUBMITMESSAGE = 'ADD_SUBMITMESSAGE'; 


export const POST_RESULTS = 'POST_RESULTS'; 

